### PR TITLE
Use Router.configure.title if current route title function returns undefined

### PR DESCRIPTION
**Pull request by sunstorymvp**
``` coffeescript
  Router.configure
    title: -> 'domain.com'
```

``` coffeescript
  @route 'post',
    path: '/path/to/post/:_id/'
    title: ->
      data = @data()
      if data then "#{data.title} - domain.com"
    data: ->
      Posts.findOne params._id
```

title will be 'domain.com' and not 'undefined - domain.com' if Posts collection returns undefined (wrong param, access denied, etc)

### CODE REVIEW

**Comment by sunstorymvp** [comment]
done )

**Comment by dr-dimitru** [comment]
@sunstorymvp merged. Thank you for contribution.

**Comment by dr-dimitru** [comment]
Published as [v0.2.2](https://github.com/VeliovGroup/Meteor-iron-router-title/releases/tag/v0.2.2)

**Comment by sunstorymvp** [comment]
Nice! thanks!

2015-07-20 17:44 GMT+03:00 dr.dimitru notifications@github.com:

**Pull request merged**
